version: '3'
services:
  metabolomicsusi-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: ${HOSTNAME:-metabolomics-usi.gnps2.org}
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: ${HOSTNAME:-metabolomics-usi.gnps2.org}
      LETSENCRYPT_EMAIL: mwang87@gmail.com
    command: /app/run_server.sh
    deploy:
      resources:
        limits:
          memory: 16000M

  metabolomicsusi-worker:
    deploy:
      resources:
        limits:
          memory: 16000M

  metabolomicsusi-redis:
    deploy:
      resources:
        limits:
          memory: 4000M

networks:
  nginx-net:
    external:
      name: nginx-net